declare module 'lucide-react' {
  import { ComponentType, SVGAttributes } from 'react';
  
  type IconProps = SVGAttributes<SVGElement> & {
    size?: string | number;
    color?: string;
    strokeWidth?: string | number;
  };
  
  export const Calendar: ComponentType<IconProps>;
  export const CheckCircle: ComponentType<IconProps>;
  export const Circle: ComponentType<IconProps>;
  export const Edit: ComponentType<IconProps>;
  export const Trash2: ComponentType<IconProps>;
  export const MoreHorizontal: ComponentType<IconProps>;
  export const Flame: ComponentType<IconProps>;
  export const Target: ComponentType<IconProps>;
  export const Plus: ComponentType<IconProps>;
  export const Minus: ComponentType<IconProps>;
  export const Play: ComponentType<IconProps>;
  export const Pause: ComponentType<IconProps>;
  export const Bell: ComponentType<IconProps>;
  export const Clock: ComponentType<IconProps>;
  export const Eye: ComponentType<IconProps>;
  export const EyeOff: ComponentType<IconProps>;
  export const Type: ComponentType<IconProps>;
  export const Code: ComponentType<IconProps>;
  export const Bold: ComponentType<IconProps>;
  export const Italic: ComponentType<IconProps>;
  export const List: ComponentType<IconProps>;
  export const Link2: ComponentType<IconProps>;
  export const Image: ComponentType<IconProps>;
  export const ChevronDown: ComponentType<IconProps>;
  export const Check: ComponentType<IconProps>;
  export const X: ComponentType<IconProps>;
  export const AlertCircle: ComponentType<IconProps>;
  export const Search: ComponentType<IconProps>;
  export const Filter: ComponentType<IconProps>;
  export const Settings: ComponentType<IconProps>;
  export const User: ComponentType<IconProps>;
  export const Home: ComponentType<IconProps>;
  export const BookOpen: ComponentType<IconProps>;
  export const Heart: ComponentType<IconProps>;
  export const Activity: ComponentType<IconProps>;
  export const Archive: ComponentType<IconProps>;
  export const BarChart3: ComponentType<IconProps>;
  export const Download: ComponentType<IconProps>;
  export const Upload: ComponentType<IconProps>;
  export const Moon: ComponentType<IconProps>;
  export const Sun: ComponentType<IconProps>;
  export const Palette: ComponentType<IconProps>;
  export const RefreshCw: ComponentType<IconProps>;
  export const Save: ComponentType<IconProps>;
  export const Menu: ComponentType<IconProps>;
  export const ChevronLeft: ComponentType<IconProps>;
  export const ChevronRight: ComponentType<IconProps>;
  export const ChevronUp: ComponentType<IconProps>;
  export const CalendarDays: ComponentType<IconProps>;
  export const ListTodo: ComponentType<IconProps>;
  export const Users: ComponentType<IconProps>;
  export const Zap: ComponentType<IconProps>;
  export const TrendingUp: ComponentType<IconProps>;
  export const Clock8: ComponentType<IconProps>;
  export const MapPin: ComponentType<IconProps>;
  export const FileText: ComponentType<IconProps>;
  export const Mail: ComponentType<IconProps>;
  export const Phone: ComponentType<IconProps>;
  export const ExternalLink: ComponentType<IconProps>;
  export const Copy: ComponentType<IconProps>;
  export const RotateCcw: ComponentType<IconProps>;
  export const MoreVertical: ComponentType<IconProps>;
  export const Star: ComponentType<IconProps>;
  export const Bookmark: ComponentType<IconProps>;
  export const Tag: ComponentType<IconProps>;
  export const Clock4: ComponentType<IconProps>;
  export const AlertTriangle: ComponentType<IconProps>;
  export const Info: ComponentType<IconProps>;
  export const CheckCircle2: ComponentType<IconProps>;
  export const XCircle: ComponentType<IconProps>;
  export const HelpCircle: ComponentType<IconProps>;
  export const Loader2: ComponentType<IconProps>;
  export const Smartphone: ComponentType<IconProps>;
  export const Monitor: ComponentType<IconProps>;
  export const Tablet: ComponentType<IconProps>;
  export const ArrowRight: ComponentType<IconProps>;
  export const ArrowLeft: ComponentType<IconProps>;
  export const ArrowUp: ComponentType<IconProps>;
  export const ArrowDown: ComponentType<IconProps>;
  export const Globe: ComponentType<IconProps>;
  export const Lock: ComponentType<IconProps>;
  export const Unlock: ComponentType<IconProps>;
  export const Wifi: ComponentType<IconProps>;
  export const WifiOff: ComponentType<IconProps>;
  export const Volume2: ComponentType<IconProps>;
  export const VolumeX: ComponentType<IconProps>;
  export const Battery: ComponentType<IconProps>;
  export const BatteryLow: ComponentType<IconProps>;
  export const Bluetooth: ComponentType<IconProps>;
  export const Camera: ComponentType<IconProps>;
  export const Mic: ComponentType<IconProps>;
  export const MicOff: ComponentType<IconProps>;
  export const Video: ComponentType<IconProps>;
  export const VideoOff: ComponentType<IconProps>;
  export const Share: ComponentType<IconProps>;
  export const Share2: ComponentType<IconProps>;
  export const MessageCircle: ComponentType<IconProps>;
  export const MessageSquare: ComponentType<IconProps>;
  export const Send: ComponentType<IconProps>;
  export const Inbox: ComponentType<IconProps>;
  export const FolderOpen: ComponentType<IconProps>;
  export const Folder: ComponentType<IconProps>;
  export const File: ComponentType<IconProps>;
  export const FileImage: ComponentType<IconProps>;
  export const FileVideo: ComponentType<IconProps>;
  export const FilePlus: ComponentType<IconProps>;
  export const FileMinus: ComponentType<IconProps>;
  export const Grid: ComponentType<IconProps>;
  export const Layers: ComponentType<IconProps>;
  export const Package: ComponentType<IconProps>;
  export const ShoppingCart: ComponentType<IconProps>;
  export const CreditCard: ComponentType<IconProps>;
  export const DollarSign: ComponentType<IconProps>;
  export const Percent: ComponentType<IconProps>;
  export const TrendingDown: ComponentType<IconProps>;
  export const PieChart: ComponentType<IconProps>;
  export const BarChart: ComponentType<IconProps>;
  export const LineChart: ComponentType<IconProps>;
  
  // Default export (might be used in some places)
  const lucideReact: {
    [key: string]: ComponentType<IconProps>;
  };
  export default lucideReact;
}